"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Override with DJANGO_SECRET_KEY in every deployed environment. The literal
# below is a development-only fallback.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-w%)xjtjj62psr_3h)@u@$@21q&_6()bqr_f)hlto1y@xi&vzi8',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', 'testserver,localhost,127.0.0.1'
    ).split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # Backs BLACKLIST_AFTER_ROTATION below: without this app a rotated-away
    # refresh token stays valid until its natural expiry.
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'products',
    'orders',
    'inventory',
    'finance',
    'audit',
    'website',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "Medware"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        # Dev fallback only - set POSTGRES_PASSWORD in any shared/deployed env.
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "5517"),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Django REST Framework configuration
try:
    import rest_framework_simplejwt  # noqa: F401
    # JWT first: DRF derives the 401-vs-403 response from the *first*
    # authenticator's WWW-Authenticate header. SessionAuthentication supplies
    # none, so listing it first turned every unauthenticated API call into a
    # 403 instead of a 401.
    DEFAULT_AUTH_CLASSES = (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
except Exception:
    DEFAULT_AUTH_CLASSES = (
        'rest_framework.authentication.SessionAuthentication',
    )

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': DEFAULT_AUTH_CLASSES,
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'mysite.exception_handlers.api_exception_handler',
    # Render DecimalFields as JSON numbers. DRF's default quotes them, which
    # contradicts every price/discount field the frontend types as `number`
    # and silently broke the numeric range filters on those columns.
    'COERCE_DECIMAL_TO_STRING': False,
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# Simple JWT settings
#
# These were previously all commented out, which left simplejwt's defaults in
# force - a 5 minute access token. Combined with a frontend that had no
# refresh-on-401 path, every request started failing with 401 about five
# minutes after signing in, regardless of the user's role. The frontend now
# refreshes and retries (the response interceptor in
# features/auth/services/auth.service.ts); these are stated explicitly so the
# lifetime is a decision rather than an inherited default.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Each refresh returns a new refresh token, so an idle-but-active session
    # keeps working while a stolen refresh token has a bounded life. Rotation
    # only bounds anything with blacklisting on - otherwise the superseded
    # token remains usable for its full REFRESH_TOKEN_LIFETIME.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

