# Generated by Django 6.0.5 on 2026-09-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='customers.customer'),
        ),
    ]
