# Generated by Django 6.0.5 on 2026-08-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_verified'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
    ]
