# Generated by Django 6.0.5 on 2026-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_add_is_verified_0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALESMAN', 'Salesman'), ('WAREHOUSE_WORKER', 'Warehouse Worker'), ('CUSTOMER', 'Customer')], default='GUEST', max_length=30),
        ),
    ]
