# Generated by Django 6.0.5 on 2026-07-01 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.bill'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='products.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='products.category'),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_categories', to='products.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill', 'product'], name='products_bi_bill_id_070b68_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['supplier', '-bill_date'], name='products_bi_supplie_157d52_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status', '-bill_date'], name='products_bi_status_685ee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('supplier', 'category')},
        ),
    ]
