# Generated by Django 6.0.5 on 2026-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_archive_order_orderproduct_ordervoucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordervoucher',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordervoucher',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='OrderVoucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
