# Generated by Django 6.0.5 on 2026-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ORDER_SUBMITTED', 'Order submitted'), ('ORDER_APPROVED', 'Order approved'), ('ORDER_REJECTED', 'Order rejected'), ('CUSTOMER_SUBMITTED', 'Customer submitted'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected')], max_length=40),
        ),
    ]
