# Generated by Django 6.0.5 on 2026-08-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_productsupplier_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_bills', to='products.supplier'),
        ),
    ]
