# Generated by Django 6.0.5 on 2026-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending manager review'), ('APPROVED', 'Approved - awaiting accountant'), ('REJECTED', 'Rejected by manager'), ('FINALIZED', 'Finalized by accountant')], default='PENDING', max_length=30),
        ),
    ]
